[package]
name = "rush-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7"
rush-analyzer = { git = "https://github.com/rush-rs/rush"}
rush-interpreter-vm = { git = "https://github.com/rush-rs/rush"}
rush-parser = { git = "https://github.com/rush-rs/rush"}
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
wasm-bindgen = "0.2.83"
