[package]
name = "rush-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
rush-analyzer = "0.1.0"
rush-interpreter-vm = "0.1.0"
rush-parser = "0.1.0"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
wasm-bindgen = "0.2.83"
